<a href="https://colab.research.google.com/github/paulosrl/NotebooksGoogleColab/blob/main/Converte_Endereco_para_Coordenada_GPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 8.3 MB/s
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.4)
Collecting fiona>=1.8
  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
     |████████████████████████████████| 16.7 MB 48.7 MB/s
Collecting pyproj>=2.2.0
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 43.0 MB/s
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.3.5)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (22.1.0)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2022.9.24)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1

In [ ]:
import geopandas as gpds
import pandas as pd

In [ ]:
gpds.tools.geocode("Belém,PA", provider='nominatim',user_agent="my-application")

,geometry,address
0,POINT (-48.46825 -1.45056),"Belém, Região Geográfica Imediata de Belém, Re..."

In [ ]:
df = pd.read_excel("AGENCIAS.xlsx")

In [ ]:
df.head()

,CNPJ,SEQUENCIAL DO CNPJ,DV DO CNPJ,NOME INSTITUIÇÃO,SEGMENTO,CÓD COMPE AG,NOME AGÊNCIA,ENDEREÇO,NÚMERO,COMPLEMENTO,BAIRRO,CEP,MUNICíPIO,UF,DATA INÍCIO,DDD,FONE,ID INSTALAÇÃO,MUNICIPIO IBGE
0,00.000.000,2,72,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,2,MANAUS ...,"R.GUILHERME MOREIRA,315",,"SUBLOJA,LOJA E 2.ANDAR ...",CENTRO,69005-300,MANAUS ...,AM,14/01/1908,92,36215500,9999994472,1302603
1,00.000.000,3,53,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,3,PRESIDENTE VARGAS ...,"AV.PRES.VARGAS,248",,1.E 2.ANDARES ...,CAMPINA,66010-900,BELEM ...,PA,1908-01-07 00:00:00,91,32164888,9999994471,1501402
2,00.000.000,4,34,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,4,SANTOS ...,"R.QUINZE DE NOVEMBRO,195",,...,CENTRO,11010-908,SANTOS ...,SP,22/08/1908,13,40097406,9999994470,3548500
3,00.000.000,5,15,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,5,CAMPOS GOYTACAZES ...,"PCA.DAS QUATRO JORNADAS,11",,MEZANINO ...,CENTRO,28010-000,CAMPOS DOS GOYTACAZES ...,RJ,26/06/1910,22,27370405,9999994469,3301009
4,00.000.000,6,4,BANCO DO BRASIL S.A. ...,Banco do Brasil - Banco Múltiplo ...,6,SALVADOR ...,"SEXTA AVENIDA,600",,SECRETARIA DA EDUCACAO-TERREO ...,CAB,41745-002,SALVADOR ...,BA,15/07/1910,71,33628803,9999994468,2927408

In [ ]:
gpds.tools.geocode(df['ENDEREÇO                                '], provider='google',user_agent="my-application")

/usr/local/lib/python3.7/dist-packages/geopy/geocoders/googlev3.py:122: UserWarning: Since July 2018 Google requires each request to have an API key. Pass a valid `api_key` to GoogleV3 geocoder to hide this warning. See https://developers.google.com/maps/documentation/geocoding/usage-and-billing
  UserWarning

                       geometry address
0      GEOMETRYCOLLECTION EMPTY    None
1      GEOMETRYCOLLECTION EMPTY    None
2      GEOMETRYCOLLECTION EMPTY    None
3      GEOMETRYCOLLECTION EMPTY    None
4      GEOMETRYCOLLECTION EMPTY    None
...                         ...     ...
17999  GEOMETRYCOLLECTION EMPTY    None
18000  GEOMETRYCOLLECTION EMPTY    None
18001  GEOMETRYCOLLECTION EMPTY    None
18002  GEOMETRYCOLLECTION EMPTY    None
18003  GEOMETRYCOLLECTION EMPTY    None

[18004 rows x 2 columns]